(function(){(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),q=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,m){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},ea=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(h){var l=typeof h;return"object"===l&&null!==h||"function"===l}function d(h){if(!t(h,f)){var l=new b;n(h,f,{value:l})}}function e(h){var l=Object[h];l&&(Object[h]=function(p){if(p instanceof b)return p;Object.isExtensible(p)&&d(p);return l(p)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),p=new a([[h,2],[l,3]]);if(2!=p.get(h)||3!=p.get(l))return!1;p.delete(h);p.set(l,4);return!p.has(h)&&4==p.get(l)}catch(K){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var m=0,g=function(h){this.g=(m+=Math.random()+1).toString();if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(h,l){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!t(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=l;return this};g.prototype.get=function(h){return c(h)&&t(h,f)?h[f][this.g]:void 0};g.prototype.has=function(h){return c(h)&&t(h,f)&&t(h[f],this.g)};
g.prototype.delete=function(h){return c(h)&&t(h,f)&&t(h[f],this.g)?delete h[f][this.g]:!1};return g});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(r([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var l=h.entries(),p=l.next();if(p.done||p.value[0]!=g||"s"!=p.value[1])return!1;p=l.next();return p.done||4!=p.value[0].x||"t"!=p.value[1]||!l.next().done?!1:!0}catch(K){return!1}}())return a;var b=new WeakMap,c=function(g){this.h={};this.g=f();
this.size=0;if(g){g=r(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.h[l.id]=[]);l.u?l.u.value=h:(l.u={next:this.g,C:this.g.C,head:this.g,key:g,value:h},l.list.push(l.u),this.g.C.next=l.u,this.g.C=l.u,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.u&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.h[g.id],g.u.C.next=g.u.next,g.u.next.C=g.u.C,g.u.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.C=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).u};c.prototype.get=function(g){return(g=d(this,g).u)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,h){for(var l=this.entries(),p;!(p=l.next()).done;)p=p.value,
g.call(h,p[1],p[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var l=h&&typeof h;"object"==l||"function"==l?b.has(h)?l=b.get(h):(l=""+ ++m,b.set(h,l)):l="p_"+h;var p=g.h[l];if(p&&t(g.h,l))for(g=0;g<p.length;g++){var K=p[g];if(h!==h&&K.key!==K.key||h===K.key)return{id:l,list:p,index:g,u:K}}return{id:l,list:p,index:-1,u:void 0}},e=function(g,h){var l=g.g;return da(function(){if(l){for(;l.head!=g.g;)l=l.C;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.C=g.next=g.head=g},m=0;return c});q("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
var fa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.entries",function(a){return a?a:function(){return fa(this,function(b,c){return[b,c]})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var m=0;!(f=b.next()).done;)e.push(c.call(d,f.value,m++))}else for(f=b.length,m=0;m<f;m++)e.push(c.call(d,b[m],m));return e}});q("Array.prototype.keys",function(a){return a?a:function(){return fa(this,function(b){return b})}});
q("Array.prototype.values",function(a){return a?a:function(){return fa(this,function(b,c){return c})}});q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push([d,b[d]]);return c}});
var u=this||self,ha=function(a,b,c){a=a.split(".");c=c||u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},v=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},ia=function(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length},ja=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ka=function(a,b,
c){return a.call.apply(a.bind,arguments)},la=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w=ka:w=la;return w.apply(null,arguments)},y=function(a,b){x.prototype[a]=b},ma=function(a,
b){function c(){}c.prototype=b.prototype;a.fb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.bb=function(d,e,f){for(var m=Array(arguments.length-2),g=2;g<arguments.length;g++)m[g-2]=arguments[g];return b.prototype[e].apply(d,m)}};function z(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}ma(z,Error);z.prototype.name="CustomError";function A(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])}ma(A,z);A.prototype.name="AssertionError";function B(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new A(""+e,f||[]);}
var C=function(a,b,c){a||B("",null,b,Array.prototype.slice.call(arguments,2));return a},na=function(a,b){throw new A("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},D=function(a,b,c){"number"!==typeof a&&B("Expected number but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2));return a},oa=function(a,b,c){"string"!==typeof a&&B("Expected string but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))},pa=function(a,b,c){Array.isArray(a)||B("Expected array but got %s: %s.",
[v(a),a],b,Array.prototype.slice.call(arguments,2))};var qa=Array.prototype.forEach?function(a,b){C(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},ra=Array.prototype.map?function(a,b){C(null!=a.length);return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},sa=Array.prototype.reduce?function(a,b,c){C(null!=
a.length);return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;qa(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},ta=Array.prototype.every?function(a,b){C(null!=a.length);return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};function ua(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function va(a){for(var b=[],c=0;c<a;c++)b[c]="";return b};var wa,E;a:{for(var xa=["CLOSURE_FLAGS"],ya=u,za=0;za<xa.length;za++)if(ya=ya[xa[za]],null==ya){E=null;break a}E=ya}var Aa=E&&E[610401301];wa=null!=Aa?Aa:!1;function Ba(){var a=u.navigator;return a&&(a=a.userAgent)?a:""}var F,Ca=u.navigator;F=Ca?Ca.userAgentData||null:null;function Da(a){return wa?F?F.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function G(a){return-1!=Ba().indexOf(a)};function H(){return wa?!!F&&0<F.brands.length:!1}function Ea(){return H()?Da("Chromium"):(G("Chrome")||G("CriOS"))&&!(H()?0:G("Edge"))||G("Silk")};var Fa=function(a){Fa[" "](a);return a};Fa[" "]=function(){};var Ga=-1!=Ba().toLowerCase().indexOf("webkit")&&!G("Edge")&&G("Mobile");try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function Ha(a,b){for(var c in a)b.call(void 0,a[c],c,a)};var Ia=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},I=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+Ia("0",Math.max(0,b-c))+a};var J=function(a){var b=document;oa(a);b="string"===typeof a?b.getElementById(a):a;return C(b,"No element found with id: "+a)},Ka=function(a,b){Ha(b,function(c,d){c&&"object"==typeof c&&c.eb&&(c=c.cb());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Ja.hasOwnProperty(d)?a.setAttribute(Ja[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},Ja={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",
height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Na=function(a,b,c){var d=arguments,e=document,f=d[1],m=La(e,String(d[0]));f&&("string"===typeof f?m.className=f:Array.isArray(f)?m.className=f.join(" "):Ka(m,f));2<d.length&&Ma(e,m,d);return m},Ma=function(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=2;e<c.length;e++){var f=c[e];if(!ia(f)||ja(f)&&0<f.nodeType)d(f);
else{a:{if(f&&"number"==typeof f.length){if(ja(f)){var m="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){m="function"==typeof f.item;break a}}m=!1}qa(m?ua(f):f,d)}}},La=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};var Qa=function(a,b){this.i=a;this.B=b;this.h=J("h5-player");Oa=this.h.clientWidth;Pa=this.h.clientHeight;this.A=J("h5-ad-container")||Na("DIV");this.m=!1;this.l=null;this.s=new window.google.ima.AdDisplayContainer(this.A,this.h);this.j=new window.google.ima.AdsLoader(this.s);this.o=[];this.g=null;this.v=J("play-button");a=this.j.getSettings();a.setPlayerType("h5_vsi");a.setDisableCustomPlaybackForIOS10Plus(!0);this.j.addEventListener(window.google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,
this.Ha,!1,this);this.j.addEventListener(window.google.ima.AdErrorEvent.Type.AD_ERROR,this.Z,!1,this);var c=null;window.addEventListener("resize",function(){this.g&&(clearTimeout(c),c=u.setTimeout(function(){Oa=this.h.clientWidth;Pa=this.h.clientHeight;this.g.resize(this.h.clientWidth,this.h.clientHeight,window.google.ima.ViewMode.NORMAL)}.bind(this),100))}.bind(this))},Oa,Pa;k=Qa.prototype;k.setVpaidMode=function(a){this.j.getSettings().setVpaidMode(Ra[a])};k.pause=function(){this.g&&this.g.pause()};
k.resume=function(){this.g&&this.g.resume()};k.setVolume=function(a){this.g&&this.g.setVolume(a)};k.getVolume=function(){return this.g?this.g.getVolume():-1};k.getCurrentTime=function(){return this.g&&this.l?this.l.getDuration()-this.g.getRemainingTime():-1};k.getDuration=function(){return this.g&&this.l?this.l.getDuration():-1};
k.Ha=function(a){this.i.log("Ads loaded.");var b=new window.google.ima.AdsRenderingSettings;b.mimeTypes=this.o;b.enablePreloading=J("preloading-true").checked;a=this.g=a.getAdsManager(this.B.g,b);a.addEventListener(window.google.ima.AdEvent.Type.CONTENT_PAUSE_REQUESTED,this.Ja,!1,this);a.addEventListener(window.google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED,this.Ka,!1,this);a.addEventListener(window.google.ima.AdErrorEvent.Type.AD_ERROR,this.Z,!1,this);for(b=0;b<Sa.length;b++)a.addEventListener(Sa[b],
this.Ga,!1,this);a.init(this.h.clientWidth,this.h.clientHeight,window.google.ima.ViewMode.NORMAL);a.start()};k.Ja=function(){var a=this.i;a.i=!0;a.g.pause()};k.Ka=function(){this.m||Ta(this.i)};
k.Ga=function(a){this.i.m&&this.i.m(a);var b=a.type;b!=window.google.ima.AdEvent.Type.AD_PROGRESS&&this.i.log("Ad event: "+b);console.log("Ad event: "+b);switch(a.type){case window.google.ima.AdEvent.Type.STARTED:this.l=a.getAd();this.l.isLinear()||Ta(this.i);break;case window.google.ima.AdEvent.Type.LOG:(a=a.getAdData())&&a.adError&&this.i.log("Non-fatal error occurred: "+a.adError.getMessage());break;case window.google.ima.AdEvent.Type.DURATION_CHANGE:this.l=a.getAd();break;case window.google.ima.AdEvent.Type.INTERACTION:this.i.log("Interaction ID: "+
a.getAdData().id);break;case window.google.ima.AdEvent.Type.PAUSED:this.v.className="play-button"}};k.Z=function(a){this.i.log("Ad error: "+a.getError().toString());this.g&&this.g.destroy();Ta(this.i)};
var Sa=[window.google.ima.AdEvent.Type.AD_METADATA,window.google.ima.AdEvent.Type.AD_PROGRESS,window.google.ima.AdEvent.Type.ALL_ADS_COMPLETED,window.google.ima.AdEvent.Type.CLICK,window.google.ima.AdEvent.Type.COMPLETE,window.google.ima.AdEvent.Type.DURATION_CHANGE,window.google.ima.AdEvent.Type.FIRST_QUARTILE,window.google.ima.AdEvent.Type.IMPRESSION,window.google.ima.AdEvent.Type.INTERACTION,window.google.ima.AdEvent.Type.LINEAR_CHANGED,window.google.ima.AdEvent.Type.LOADED,window.google.ima.AdEvent.Type.LOG,
window.google.ima.AdEvent.Type.MIDPOINT,window.google.ima.AdEvent.Type.PAUSED,window.google.ima.AdEvent.Type.RESUMED,window.google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED,window.google.ima.AdEvent.Type.SKIPPED,window.google.ima.AdEvent.Type.STARTED,window.google.ima.AdEvent.Type.THIRD_QUARTILE,window.google.ima.AdEvent.Type.USER_CLOSE,window.google.ima.AdEvent.Type.VOLUME_CHANGED,window.google.ima.AdEvent.Type.VOLUME_MUTED],Ra={"vpaid-enabled":window.google.ima.ImaSdkSettings.VpaidMode.ENABLED,"vpaid-insecure":window.google.ima.ImaSdkSettings.VpaidMode.INSECURE,
"vpaid-disabled":window.google.ima.ImaSdkSettings.VpaidMode.DISABLED};var Ua=function(){this.g=J("h5-player");this.h=null},Va=function(a,b){Ga?(a.h=b,a.g.addEventListener("loadedmetadata",a.h,!1),a.g.load()):b()},Wa=function(a){a.h&&a.g.removeEventListener("loadedmetadata",a.h,!1)};k=Ua.prototype;k.load=function(){this.g.load()};k.play=function(){this.g.play()};k.pause=function(){this.g.pause()};k.setVolume=function(a){this.g.volume=a};k.getCurrentTime=function(){return this.g.currentTime};k.getDuration=function(){return this.g.duration};var L=function(){this.H=this.A=this.i=!1;this.m=this.s=this.F=null;this.g=new Ua;this.h=new Qa(this,this.g);this.B=this.v="";this.o=[];this.l=this.j=0;var a=w(this.I,this);this.g.g.addEventListener("ended",a,!1)};L.prototype.setVpaidMode=function(a){this.h.setVpaidMode(a)};L.prototype.setVolume=function(a){this.h.setVolume(a);this.g.setVolume(a)};
var Ya=function(a,b){a.v=b;Xa(a);Va(a.g,function(){Wa(a.g);var c=a.h,d=a.v;if(d.includes("%%"))c.i.log("The ad contains macros such as %%WINNING_PRICE%%. Please expand all macros prior to testing ad tags in VSI player.");else{var e=new window.google.ima.AdsRequest;e.adTagUrl=d;e.linearAdSlotWidth=e.nonLinearAdSlotWidth=Oa;e.linearAdSlotHeight=e.nonLinearAdSlotHeight=Pa;c.j.requestAds(e)}})},Za=function(a,b){a.B=b;Xa(a);Va(a.g,function(){Wa(a.g);var c=a.h,d=a.B,e=new window.google.ima.AdsRequest;Oa=
c.h.clientWidth;Pa=c.h.clientHeight;e.adsResponse=d;e.linearAdSlotWidth=e.nonLinearAdSlotWidth=c.h.clientWidth;e.linearAdSlotHeight=e.nonLinearAdSlotHeight=c.h.clientHeight;c.j.requestAds(e)})},Xa=function(a){var b=a.h;b.g&&b.g.destroy();b.j&&b.j.contentComplete();b.m=!1;a.h.o=a.o;setInterval(w(a.G,a),250);a.A||(a.g.load(),a.h.s.initialize(),a.A=!0);a.H&&(a.g.g.currentTime=0);a.H=!0};L.prototype.play=function(){setInterval(w(this.G,this),250);this.i?this.h.resume():this.g.play()};
L.prototype.pause=function(){this.i?this.h.pause():this.g.pause()};L.prototype.log=function(a){this.F(a)};var Ta=function(a){a.g.play();a.i=!1};L.prototype.G=function(){this.i?(this.j=this.h.getCurrentTime(),this.l=this.h.getDuration()):(this.j=this.g.getCurrentTime(),this.l=this.g.getDuration());this.s({currentTime:this.j,duration:this.l})};L.prototype.I=function(){var a=this.h;a.m=!0;a.j.contentComplete()};ha("VideoSuiteInspector.players.h5player.HTML5Player",L);!G("Android")||Ea();Ea();G("Safari")&&(Ea()||(H()?0:G("Coast"))||(H()?0:G("Opera"))||(H()?0:G("Edge"))||(H()?Da("Microsoft Edge"):G("Edg/"))||H()&&Da("Opera"));C(!0);var $a="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0,ab=Object.getOwnPropertyDescriptor(Array.prototype,"Fa");
Object.defineProperties(Array.prototype,{Fa:{get:function(){function a(e,f){e&b&&c.push(f)}var b=bb(this),c=[];a(1,"IS_REPEATED_FIELD");a(2,"IS_IMMUTABLE_ARRAY");a(4,"IS_API_FORMATTED");a(8,"ONLY_MUTABLE_VALUES");a(16,"MUTABLE_REFERENCES_ARE_OWNED");a(32,"CONSTRUCTED");a(64,"TRANSFERRED");a(128,"IS_FIXED_GROUP");var d=c.join(",");return ab?ab.get.call(this)+"|"+d:d},configurable:!0,enumerable:!1}});
function bb(a){pa(a,"state is only maintained on arrays.");var b;$a?b=a[$a]:b=a.g;return null==b?0:b};var cb=function(){throw Error("please construct maps as mutable then call toImmutable");};
if("undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance){var db=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},eb={};Object.defineProperties(cb,(eb[Symbol.hasInstance]={value:db,configurable:!1,writable:!1,enumerable:!1},eb));C(cb[Symbol.hasInstance]===db,"defineProperties did not work: was it monkey-patched?")};if("undefined"!==typeof Proxy){var M=fb;new Proxy({},{getPrototypeOf:M,setPrototypeOf:M,isExtensible:M,preventExtensions:M,getOwnPropertyDescriptor:M,defineProperty:M,has:M,get:M,set:M,deleteProperty:M,apply:M,construct:M})}function fb(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");throw Error();};function gb(){};(function(){var a=u.jspbGetTypeName;u.jspbGetTypeName=a?function(b){return a(b)||void 0}:gb})();var hb=function(a,b){this.name=a;this.value=b};hb.prototype.toString=function(){return this.name};var ib=new hb("OFF",Infinity),jb=new hb("WARNING",900),kb=new hb("CONFIG",700),lb=function(){},mb,nb=function(a,b,c){this.reset(a||ib,b,c,void 0,void 0)};nb.prototype.reset=function(a,b){this.g=b};nb.prototype.getMessage=function(){return this.g};
var ob=function(a,b){this.g=null;this.j=[];this.h=(void 0===b?null:b)||null;this.i=[];this.l={g:function(){return a}}},pb=function(a){if(a.g)return a.g;if(a.h)return pb(a.h);na("Root logger has no level set.");return ib},qb=function(a,b){for(;a;)a.j.forEach(function(c){c(b)}),a=a.h},rb=function(){this.entries={};var a=new ob("");a.g=kb;this.entries[""]=a},sb,N=function(a,b){var c=a.entries[b];if(c)return c;c=N(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new ob(b,c);a.entries[b]=d;c.i.push(d);
return d},O=function(){sb||(sb=new rb);return sb};N(O(),"contentads.shared.adtech.iabtcfv2.js.PublisherTcCodec");N(O(),"contentads.shared.adtech.iabtcfv2.js.TcfCoreStringCodec");var tb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),ub=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};/*

 SPDX-License-Identifier: Apache-2.0
*/
var vb=[],wb=function(a){var b=N(O(),"safevalues").l;if(b){a="A URL with content '"+a+"' was sanitized away.";var c=jb,d;if(d=b)if(d=b&&c){d=c.value;var e=b?pb(N(O(),b.g())):ib;d=d>=e.value}d&&(c=c||ib,d=N(O(),b.g()),"function"===typeof a&&(a=a()),mb||(mb=new lb),b=new nb(c,a,b.g()),qb(d,b))}};-1===vb.indexOf(wb)&&vb.push(wb);function xb(a){var b,c;return null!=(c=null==(b=/https?:\/\/[^\/]+/.exec(a))?void 0:b[0])?c:""};var P=function(a){this.h=this.o=this.j="";this.s=null;this.m=this.g="";this.l=!1;var b;a instanceof P?(this.l=a.l,yb(this,a.j),this.o=a.o,this.h=a.h,zb(this,a.s),this.g=a.g,Ab(this,Bb(a.i)),this.m=a.m):a&&(b=String(a).match(tb))?(this.l=!1,yb(this,b[1]||"",!0),this.o=Q(b[2]||""),this.h=Q(b[3]||"",!0),zb(this,b[4]),this.g=Q(b[5]||"",!0),Ab(this,b[6]||"",!0),this.m=Q(b[7]||"")):(this.l=!1,this.i=new R(null,this.l))};
P.prototype.toString=function(){var a=[],b=this.j;b&&a.push(S(b,Cb,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(S(b,Cb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.g)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(S(c,"/"==c.charAt(0)?Db:Eb,!0));(c=this.i.toString())&&a.push("?",c);(c=this.m)&&a.push("#",S(c,Fb));return a.join("")};
P.prototype.resolve=function(a){var b=new P(this),c=!!a.j;c?yb(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.h;c?b.h=a.h:c=null!=a.s;var d=a.g;if(c)zb(b,a.s);else if(c=!!a.g){if("/"!=d.charAt(0))if(this.h&&!this.g)d="/"+d;else{var e=b.g.lastIndexOf("/");-1!=e&&(d=b.g.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],m=0;m<e.length;){var g=e[m++];"."==g?d&&m==e.length&&f.push(""):".."==g?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&m==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?b.g=d:c=""!==a.i.toString();c?Ab(b,Bb(a.i)):c=!!a.m;c&&(b.m=a.m);return b};
var yb=function(a,b,c){a.j=c?Q(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},zb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},Ab=function(a,b,c){b instanceof R?(a.i=b,Gb(a.i,a.l)):(c||(b=S(b,Hb)),a.i=new R(b,a.l))},Q=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},S=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ib),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ib=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Cb=/[#\/\?@]/g,Eb=/[#\?:]/g,Db=/[#\?]/g,Hb=/[#\?@]/g,Fb=/#/g,R=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},T=function(a){a.g||(a.g=new Map,a.h=0,a.i&&ub(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};R.prototype.add=function(a,b){T(this);this.i=null;a=U(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h=D(this.h)+1;return this};
var Jb=function(a,b){T(a);b=U(a,b);a.g.has(b)&&(a.i=null,a.h=D(a.h)-a.g.get(b).length,a.g.delete(b))},Kb=function(a,b){T(a);b=U(a,b);return a.g.has(b)};R.prototype.forEach=function(a,b){T(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var Lb=function(a,b){T(a);var c=[];if("string"===typeof b)Kb(a,b)&&(c=c.concat(a.g.get(U(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
R.prototype.set=function(a,b){T(this);this.i=null;a=U(this,a);Kb(this,a)&&(this.h=D(this.h)-this.g.get(a).length);this.g.set(a,[b]);this.h=D(this.h)+1;return this};R.prototype.get=function(a,b){if(!a)return b;a=Lb(this,a);return 0<a.length?String(a[0]):b};
R.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Lb(this,d);for(var f=0;f<d.length;f++){var m=e;""!==d[f]&&(m+="="+encodeURIComponent(String(d[f])));a.push(m)}}return this.i=a.join("&")};
var Bb=function(a){var b=new R;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},U=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Gb=function(a,b){b&&!a.j&&(T(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Jb(this,d),Jb(this,e),0<c.length&&(this.i=null,this.g.set(U(this,e),ua(c)),this.h=D(this.h)+c.length))},a));a.j=b};N(O(),"google3.javascript.ads.imalib.common.host_utils");function Mb(a){var b=[""];if(!a)return null;a=a.toLowerCase().replace("-","_");if(b.includes(a))return a;a=(a=a.match(/^\w{2,3}([-_]|$)/))?a[0].replace(/[_-]/g,""):"";return b.includes(a)?a:null};/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var Nb="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");var Ob=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)"),Sb=function(a){a=a||Pb();for(var b=new Qb(u.location.href,!1),c=null,d=a.length-1,e=d;0<=e;--e){var f=a[e];!c&&Ob.test(f.url)&&(c=f);if(f.url&&!f.K){b=f;break}}e=null;f=a.length&&a[d].url;0!=b.depth&&f&&(e=a[d]);return new Rb(b,e,c)},Pb=function(){var a=u,b=[],c=null;do{var d=a;try{var e;if(e=!!d&&null!=d.location.href)b:{try{Fa(d.foo);e=!0;break b}catch(g){}e=!1}var f=e}catch(g){f=!1}if(f){var m=d.location.href;c=d.document&&
d.document.referrer||null}else m=c,c=null;b.push(new Qb(m||""));try{a=d.parent}catch(g){a=null}}while(a&&d!=a);d=0;for(a=b.length-1;d<=a;++d)b[d].depth=a-d;d=u;if(d.location&&d.location.ancestorOrigins&&d.location.ancestorOrigins.length==b.length-1)for(a=1;a<b.length;++a)m=b[a],m.url||(m.url=d.location.ancestorOrigins[a-1]||"",m.K=!0);return b},Rb=function(a,b,c){this.h=a;this.i=b;this.g=c},Qb=function(a,b){this.url=a;this.K=!!b;this.depth=null};var Tb=function(a,b){this.g=a;this.depth=b},Vb=function(){var a=Pb(),b=Math.max(a.length-1,0),c=Sb(a);a=c.h;var d=c.i,e=c.g,f=[];c=function(g,h){return null==g?h:g};e&&f.push(new Tb([e.url,e.K?2:0],c(e.depth,1)));d&&d!=e&&f.push(new Tb([d.url,2],0));a.url&&a!=e&&f.push(new Tb([a.url,0],c(a.depth,b)));var m=ra(f,function(g,h){return f.slice(0,f.length-h)});!a.url||(e||d)&&a!=e||(d=xb(a.url))&&m.push([new Tb([d,1],c(a.depth,b))]);m.push([]);ra(m,function(g){return Ub(b,g)})};
function Ub(a,b){C(ta(b,function(e){return 0<=e.depth}));var c=sa(b,function(e,f){return Math.max(e,f.depth)},-1),d=va(c+2);d[0]=a;qa(b,function(e){return d[e.depth+1]=e.g});return d};var x=function(){this.i="always";this.s=4;this.B=null;this.g=1;this.h=!0;this.locale="en";this.o=!1;this.A=this.v="";this.l=!1;this.j=!0;for(var a=Array(36),b=0,c,d=0;36>d;d++)8==d||13==d||18==d||23==d?a[d]="-":14==d?a[d]="4":(2>=b&&(b=33554432+16777216*Math.random()|0),c=b&15,b>>=4,a[d]=Nb[19==d?c&3|8:c]);this.m={};try{Vb()}catch(e){}},Wb=function(a){a=null==a?"":String(a);/^[\s\xa0]*$/.test(a)||(a=a.substring(0,20));return a};k=x.prototype;k.setCompanionBackfill=function(a){this.i=a};
k.getCompanionBackfill=function(){return this.i};k.setNumRedirects=function(a){this.s=a};k.getNumRedirects=function(){return this.s};k.setPpid=function(a){this.B=a};k.getPpid=function(){return this.B};k.setVpaidAllowed=function(a){"boolean"===typeof a&&(this.g=a?1:0)};k.setVpaidMode=function(a){this.g=a};k.Da=function(){return this.g};k.setAutoPlayAdBreaks=function(a){this.h=a};k.Ea=function(){return this.h};k.Sa=function(a){this.o=a};k.Ca=function(){return this.o};
k.setLocale=function(a){if(a=Mb(a))this.locale=a};k.getLocale=function(){return this.locale};k.setPlayerType=function(a){this.v=Wb(a)};k.getPlayerType=function(){return this.v};k.setPlayerVersion=function(a){this.A=Wb(a)};k.getPlayerVersion=function(){return this.A};k.Ta=function(){};k.Ua=function(){};k.setDisableCustomPlaybackForIOS10Plus=function(a){this.l=a};k.getDisableCustomPlaybackForIOS10Plus=function(){return this.l};k.isCookiesEnabled=function(){return this.j};
k.setCookiesEnabled=function(a){null!=a&&(this.j=a)};k.setSessionId=function(){};k.Ra=function(){};k.Ba=function(){return!0};k.setFeatureFlags=function(a){this.m=a};k.getFeatureFlags=function(){return this.m};y("getFeatureFlags",x.prototype.getFeatureFlags);y("setFeatureFlags",x.prototype.setFeatureFlags);y("getDisableFlashAds",x.prototype.Ba);y("setDisableFlashAds",x.prototype.Ra);y("setSessionId",x.prototype.setSessionId);y("setCookiesEnabled",x.prototype.setCookiesEnabled);
y("isCookiesEnabled",x.prototype.isCookiesEnabled);y("getDisableCustomPlaybackForIOS10Plus",x.prototype.getDisableCustomPlaybackForIOS10Plus);y("setDisableCustomPlaybackForIOS10Plus",x.prototype.setDisableCustomPlaybackForIOS10Plus);y("setStreamCorrelator",x.prototype.Ua);y("setPageCorrelator",x.prototype.Ta);y("getPlayerVersion",x.prototype.getPlayerVersion);y("setPlayerVersion",x.prototype.setPlayerVersion);y("getPlayerType",x.prototype.getPlayerType);y("setPlayerType",x.prototype.setPlayerType);
y("getLocale",x.prototype.getLocale);y("setLocale",x.prototype.setLocale);y("getIsVpaidAdapter",x.prototype.Ca);y("setIsVpaidAdapter",x.prototype.Sa);y("isAutoPlayAdBreaks",x.prototype.Ea);y("setAutoPlayAdBreaks",x.prototype.setAutoPlayAdBreaks);y("getVpaidMode",x.prototype.Da);y("setVpaidMode",x.prototype.setVpaidMode);y("setVpaidAllowed",x.prototype.setVpaidAllowed);y("getPpid",x.prototype.getPpid);y("setPpid",x.prototype.setPpid);y("getNumRedirects",x.prototype.getNumRedirects);
y("setNumRedirects",x.prototype.setNumRedirects);y("getCompanionBackfill",x.prototype.getCompanionBackfill);y("setCompanionBackfill",x.prototype.setCompanionBackfill);new x;var Xb=function(a){var b=La(document,"BODY");b.textContent=a;C(b.innerHTML==b.textContent,"String has HTML original: %s, escaped: %s",a,b.innerHTML);return a};var Yb={da:["BC","AD"],ca:["Before Christ","Anno Domini"],ga:"JFMAMJJASOND".split(""),oa:"JFMAMJJASOND".split(""),fa:"January February March April May June July August September October November December".split(" "),na:"January February March April May June July August September October November December".split(" "),ka:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),qa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),xa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
sa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ma:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ra:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Xa:"SMTWTFS".split(""),pa:"SMTWTFS".split(""),la:["Q1","Q2","Q3","Q4"],ia:["1st quarter","2nd quarter","3rd quarter","4th quarter"],aa:["AM","PM"],Va:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],Za:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],Wa:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],M:6,
ab:[5,6],N:5},Zb=Yb;Zb=Yb;var $b=function(a,b,c,d,e){a=new Date(a,b,c);e=e||0;return a.valueOf()+864E5*(((void 0!==d?d:3)-e+7)%7-((a.getDay()+6)%7-e+7)%7)};var ac=function(){},cc=function(a){if("number"==typeof a){var b=new ac;b.l=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",I(c,2));c=d.join("")}b.i=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=bc(a);b.j=[c,c];b.g={Ya:a,Y:a};b.h=[];return b}b=new ac;b.i=a.id;b.l=-a.std_offset;b.j=a.names;b.g=a.names_ext;b.h=a.transitions;return b},bc=function(a){var b=
["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(I(Math.floor(a/60)%100,2),":",I(a%60,2));return b.join("")},dc=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.h.length&&b>=a.h[c];)c+=2;return 0==c?0:a.h[c-1]},ec=function(a,b){a=a.l-dc(a,b);return-1440===a?0:a};var hc=function(){C(!0,"Pattern must be defined");C(void 0!==Zb,"goog.i18n.DateTimeSymbols or explicit symbols must be defined");this.h=[];this.g=Zb;var a="mm:ss";for(fc&&(a=a.replace(/\u200f/g,""));a;){for(var b=a,c=0;c<gc.length;++c){var d=a.match(gc[c]);if(d){var e=d[0];a=a.substring(e.length);0==c&&("''"==e?e="'":(e=e.substring(1,"'"==d[1]?e.length-1:e.length),e=e.replace(/''/g,"'")));this.h.push({text:e,type:c});break}}if(b===a)throw Error("Malformed pattern part: "+a);}},gc=[/^'(?:[^']|'')*('|$)/,
/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|b+|B+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEabBhKHcLQdmsvVwzZ]+/],V=function(a){return a.getHours?a.getHours():0},jc=function(a,b){if(!b)throw Error("The date to format must be non-null.");for(var c=[],d=0;d<a.h.length;++d){var e=a.h[d].text;1==a.h[d].type?c.push(ic(a,e,b,b,b)):c.push(e)}return c.join("")},W=function(a,b){b=String(b);a=a.g||Zb;if(void 0!==a.ya){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.ya+
e-48):b.charAt(d))}b=c.join("")}return b},fc=!1,X=function(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("The date to format has no time (probably a goog.date.Date). Use Date or goog.date.DateTime, or use a pattern without time fields.");},kc=function(a,b){X(b);b=V(b);return a.g.aa[12<=b&&24>b?1:0]},ic=function(a,b,c,d,e){var f=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=f?a.g.ca[c]:a.g.da[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==f&&(c%=100),W(a,
I(c,f));case "Y":return c=(new Date($b(d.getFullYear(),d.getMonth(),d.getDate(),a.g.N,a.g.M))).getFullYear(),0>c&&(c=-c),2==f&&(c%=100),W(a,I(c,f));case "M":a:switch(c=d.getMonth(),f){case 5:f=a.g.ga[c];break a;case 4:f=a.g.fa[c];break a;case 3:f=a.g.ka[c];break a;default:f=W(a,I(c+1,f))}return f;case "k":return X(e),W(a,I(V(e)||24,f));case "S":return W(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,f)).slice(2)+(3<f?I(0,f-3):""));case "E":return c=d.getDay(),4<=f?a.g.xa[c]:a.g.ma[c];case "a":return kc(a,
e);case "b":return kc(a,e);case "B":return kc(a,e);case "h":return X(e),W(a,I(V(e)%12||12,f));case "K":return X(e),W(a,I(V(e)%12,f));case "H":return X(e),W(a,I(V(e),f));case "c":a:switch(c=d.getDay(),f){case 5:f=a.g.pa[c];break a;case 4:f=a.g.sa[c];break a;case 3:f=a.g.ra[c];break a;default:f=W(a,I(c,1))}return f;case "L":a:switch(c=d.getMonth(),f){case 5:f=a.g.oa[c];break a;case 4:f=a.g.na[c];break a;case 3:f=a.g.qa[c];break a;default:f=W(a,I(c+1,f))}return f;case "Q":return c=Math.floor(d.getMonth()/
3),4>f?a.g.la[c]:a.g.ia[c];case "d":return W(a,I(d.getDate(),f));case "m":return X(e),W(a,I(e.getMinutes?e.getMinutes():0,f));case "s":return X(e),W(a,I(e.getSeconds(),f));case "v":return cc(c.getTimezoneOffset()).i;case "V":return a=cc(c.getTimezoneOffset()),2>=f?a.i:0<dc(a,c)?void 0!==a.g.ba?a.g.ba:a.g.DST_GENERIC_LOCATION:void 0!==a.g.Y?a.g.Y:a.g.STD_GENERIC_LOCATION;case "w":return c=$b(e.getFullYear(),e.getMonth(),e.getDate(),a.g.N,a.g.M),W(a,I(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),
0,1)).valueOf())/864E5)/7)+1,f));case "z":return a=cc(c.getTimezoneOffset()),4>f?a.j[0<dc(a,c)?2:0]:a.j[0<dc(a,c)?3:1];case "Z":return b=cc(c.getTimezoneOffset()),4>f?(f=-ec(b,c),a=[0>f?"-":"+"],f=Math.abs(f),a.push(I(Math.floor(f/60)%100,2),I(f%60,2)),f=a.join("")):f=W(a,bc(ec(b,c))),f;default:return""}};var Y=function(a,b){this.g=a;this.l=!1;this.X=J("vast-tag-radio");this.h=J("vast-tag-url");this.J=J("vast-xml");this.wa=J("http-warning");this.O=J("advanced-controls-arrow");this.s=J("share-link-button");this.W=J("shorten-share-link-checkbox-div");this.I=J("shorten-share-link-checkbox");this.m=J("share-link-text");this.P=J("advanced-controls");this.o=J("play-button");this.ja=J("current-time");this.ta=J("duration-time");this.H=J("progress-list");this.va=J("play-progress");this.A=J("volume-button");
this.v=J("report-events");this.F="";this.G=b;this.B=this.U=!1;this.j=this.i=0;this.T=[];this.R=[];lc(this);mc(this);if(a=this.G)if(a=(new P(a)).i.get("tag"))this.h.value=decodeURIComponent(a.replace(/\+/g," "));a=w(this.ua,this);this.g.F=a;a=w(this.ea,this);this.g.s=a;a=w(this.za,this);this.g.m=a},lc=function(a){var b=J("companion-section");nc.forEach(function(c){var d=Na("DIV");d.id=c.name;d.className="vsi-companion-ad";d.name=c.name;b.appendChild(d);a.T.push(d);googletag.defineUnit(c.name,["fluid",
[c.width,c.height]],c.name).addService(googletag.companionAds())});googletag.pubads().collapseEmptyDivs();googletag.enableServices()},mc=function(a){[{id:"sample-tag-link",D:a.Na},{id:"vast-xml-radio",D:a.Qa},{id:"advanced-controls-header",D:a.Ia},{id:"test-ad-button",D:a.Oa},{id:"clear-log-button",D:a.ha}].forEach(function(b){var c=J(b.id);Z(a,c,b.D)});Z(a,a.X,a.Pa);Z(a,a.s,a.V);Z(a,a.I,a.V);Z(a,a.o,a.La);Z(a,a.H,a.Ma);Z(a,a.A,a.L);a.A.value="max";a.F=a.h.value;setInterval(w(a.Aa,a),100)};k=Y.prototype;
k.destroy=function(){this.R.forEach(function(a){var b=a.element;a=a.D;b.addEventListener?b.removeEventListener("click",a,!1):b.attachEvent&&b.detachEvent("onclick",a)})};k.Pa=function(){oc(this,!0);pc(this);this.h.style.display="inline";this.J.style.display="none"};k.Qa=function(){oc(this,!1);pc(this);this.h.style.display="none";this.J.style.display="inline"};k.Na=function(){this.h.value="https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator="};
k.Aa=function(){if(this.F!=this.h.value){var a=new P(this.h.value);this.wa.style.display="http"==a.j?"inline-block":"none";this.F=this.h.value}};k.Oa=function(){qc(this);rc(this);sc(this);this.X.checked?Ya(this.g,this.h.value):Za(this.g,this.J.value);this.o.className="pause-button"};
var rc=function(a){var b=[];[].concat(ea(document.getElementsByClassName("mime-checkbox"))).forEach(function(c){c.checked&&b.push(c.getAttribute("id"))});a.g.o=b},sc=function(a){[].concat(ea(document.getElementsByName("vpaid-radio-group"))).forEach(function(b){b.checked&&a.g.setVpaidMode(b.id)})};
Y.prototype.V=function(){this.W.style.display="inline";var a="https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector";this.G?a=this.G:document.referrer&&document.referrer.includes("vastinspector")&&(a=document.referrer);if(a){a=new P(a);if(""!==encodeURIComponent(this.h.value)){var b=encodeURIComponent(this.h.value);a.i.set("tag",b)}a=a.toString();this.I.checked?tc(this,a):uc(this,a)}else this.m.value="Error: could not generate sharable URL"};
var vc=function(a,b){gapi.client.setApiKey("AIzaSyDhwO-mwC66FOUtx1gVxH9nnWWz1je5UlI");gapi.client.load("urlshortener","v1",function(){a.U=!0;tc(a,b)})},tc=function(a,b){a.U?gapi.client.urlshortener.url.insert({resource:{longUrl:b}}).execute(function(c){uc(a,c.id)}):vc(a,b)},uc=function(a,b){a.m.value=b;a.m.style.display="block";a.m.select()},pc=function(a){a.m.value="";a.m.style.display="none"},oc=function(a,b){b?(a.s.disabled="",a.s.classList.add("button-blue")):(a.s.disabled="disabled",a.s.classList.remove("button-blue"),
a.W.style.display="none",a.I.checked="")},qc=function(a){a.T.forEach(function(b){b.textContent=""})};k=Y.prototype;k.Ia=function(){this.B?(this.O.textContent="\u25b8",this.P.style.display="none"):(this.O.textContent="\u25be",this.P.style.display="block");this.B=!this.B};k.La=function(){"play-button"===this.o.className?(this.o.className="pause-button",this.g.play()):(this.o.className="play-button",this.g.pause())};
k.Ma=function(a){if(this.j&&this.i){var b=this.H.getBoundingClientRect().left;a=(a.clientX-b)/this.H.clientWidth;this.i=0>a?0:1<a?this.j:this.j*a;this.i=Math.round(this.i);a=this.g;a.i||(a.g.g.currentTime=this.i);wc(this)}};k.L=function(){(this.l=!this.l)?(this.g.setVolume(0),this.A.value="off"):(this.g.setVolume(1),this.A.value="max")};
k.ea=function(a){this.i=-1<a.currentTime?a.currentTime:0;this.j=-1<a.duration?a.duration:0;a=new hc;this.ja.textContent=Xb(jc(a,new Date(0,0,0,0,0,this.i)));this.ta.textContent=Xb(jc(a,new Date(0,0,0,0,0,this.j)));wc(this)};k.za=function(a){switch(a.type){case window.google.ima.AdEvent.Type.VOLUME_MUTED:this.l||this.L();break;case window.google.ima.AdEvent.Type.VOLUME_CHANGED:a=this.g.h.getVolume(),(0==a&&!this.l||0!=a&&this.l)&&this.L()}};
var wc=function(a){a.va.style.width=0<a.j?Math.round(a.i/a.j*100)+"%":"0"};Y.prototype.ua=function(a){a="("+(new Date).toLocaleTimeString()+") "+a;var b=document.createElement("li");b.appendChild(document.createTextNode(a));this.v.appendChild(b);this.v.scrollTop=this.v.scrollHeight};Y.prototype.ha=function(){this.v.textContent=""};
var Z=function(a,b,c){c=c.bind(a);b.addEventListener?b.addEventListener("click",c,!1):b.attachEvent&&b.attachEvent("onclick",c);a.R.push({element:b,D:c})},nc=[{name:"leaderboard",width:728,height:90},{name:"mediumRectangle",width:300,height:250},{name:"rectangle",width:180,height:150},{name:"button2",width:120,height:60},{name:"microBar",width:88,height:31},{name:"smallRectangle",width:300,height:60},{name:"threeByOne",width:300,height:100},{name:"mobileBanner",width:320,height:50},{name:"smallBanner",
width:468,height:60},{name:"halfPageAd",width:300,height:600},{name:"wideSkyscraper",width:160,height:600}];ha("VideoSuiteInspector.ui.UserInterface",Y,window);}).call(this);
})();