(function(){(function(){var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),q=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,g){this.g=f;p(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},ea=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!t(k,f)){var l=new b;p(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(H){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(k){this.g=(g+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};h.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};h.prototype.get=function(k){return c(k)&&t(k,f)?k[f][this.g]:void 0};h.prototype.has=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)};
h.prototype.delete=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)?delete k[f][this.g]:!1};return h});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(r([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(H){return!1}}())return a;var b=new WeakMap,c=function(h){this[0]={};this[1]=
f();this.size=0;if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.A?l.A.value=k:(l.A={next:this[1],F:this[1].F,head:this[1],key:h,value:k},l.list.push(l.A),this[1].F.next=l.A,this[1].F=l.A,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.A&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.A.F.next=h.A.next,h.A.next.F=h.A.F,h.A.head=
null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].F=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).A};c.prototype.get=function(h){return(h=d(this,h).A)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,h.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++g,b.set(k,l)):l="p_"+k;var n=h[0][l];if(n&&t(h[0],l))for(h=0;h<n.length;h++){var H=n[h];if(k!==k&&H.key!==H.key||k===H.key)return{id:l,list:n,index:h,A:H}}return{id:l,list:n,index:-1,A:void 0}},e=function(h,k){var l=h[1];return da(function(){if(l){for(;l.head!=h[1];)l=l.F;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};
l=null}return{done:!0,value:void 0}})},f=function(){var h={};return h.F=h.next=h.head=h},g=0;return c});var fa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.keys",function(a){return a?a:function(){return fa(this,function(b){return b})}});
q("Array.prototype.entries",function(a){return a?a:function(){return fa(this,function(b,c){return[b,c]})}});q("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});q("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push(b[d]);return c}});q("Array.prototype.values",function(a){return a?a:function(){return fa(this,function(b,c){return c})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push([d,b[d]]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var u=this||self,ha=function(a,b,c){a=a.split(".");c=c||u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},v=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},ia=function(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length},ja=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ka=function(a,b,
c){return a.call.apply(a.bind,arguments)},la=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return w.apply(null,arguments)},ma=function(a,b){function c(){}c.prototype=
b.prototype;a.rb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qb=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};function x(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}ma(x,Error);x.prototype.name="CustomError";function na(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");x.call(this,c+a[d])}ma(na,x);na.prototype.name="AssertionError";function y(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new na(""+e,f||[]);}
var z=function(a,b,c){a||y("",null,b,Array.prototype.slice.call(arguments,2));return a},A=function(a,b,c){"number"!==typeof a&&y("Expected number but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2));return a},oa=function(a,b,c){"string"!==typeof a&&y("Expected string but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))},pa=function(a,b,c){Array.isArray(a)||y("Expected array but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))};var qa=Array.prototype.forEach?function(a,b){z(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function ra(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var sa,B;a:{for(var ta=["CLOSURE_FLAGS"],C=u,ua=0;ua<ta.length;ua++)if(C=C[ta[ua]],null==C){B=null;break a}B=C}var va=B&&B[610401301];sa=null!=va?va:!1;function wa(){var a=u.navigator;return a&&(a=a.userAgent)?a:""}var D,xa=u.navigator;D=xa?xa.userAgentData||null:null;function ya(a){return sa?D?D.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function E(a){return-1!=wa().indexOf(a)};function F(){return sa?!!D&&0<D.brands.length:!1}function za(){return F()?ya("Chromium"):(E("Chrome")||E("CriOS"))&&!(F()?0:E("Edge"))||E("Silk")};var Aa=-1!=wa().toLowerCase().indexOf("webkit")&&!E("Edge")&&E("Mobile");try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function Ba(a,b){for(var c in a)b.call(void 0,a[c],c,a)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Ca={};var Da=function(a){if(Ca!==Ca)throw Error("Bad secret");this.g=a};Da.prototype.toString=function(){return this.g};new Da("about:blank");new Da("about:invalid#zClosurez");var Ea=[],Fa=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};-1===Ea.indexOf(Fa)&&Ea.push(Fa);var Ga={},Ha=function(){if(Ga!==Ga)throw Error("SafeStyle is not meant to be built directly");};Ha.prototype.toString=function(){return"".toString()};new Ha;var Ia={},Ja=function(){if(Ia!==Ia)throw Error("SafeStyleSheet is not meant to be built directly");};Ja.prototype.toString=function(){return"".toString()};new Ja;var Ka={},La=function(){var a=u.trustedTypes&&u.trustedTypes.emptyHTML||"";if(Ka!==Ka)throw Error("SafeHtml is not meant to be built directly");this.g=a};La.prototype.toString=function(){return this.g.toString()};new La;var Ma=function(){this.name="CONFIG";this.value=700};Ma.prototype.toString=function(){return this.name};var Na=new Ma,Oa=function(){this.g=null;this.i=[]},Pa=function(){this.entries={};var a=new Oa;a.g=Na;this.entries[""]=a},Qa,Ra=function(a,b,c){var d=a.entries[b];if(d)return void 0!==c&&(d.g=c),d;d=Ra(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var e=new Oa;a.entries[b]=e;d.i.push(e);void 0!==c&&(e.g=c);return e};var Sa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},G=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+Sa("0",Math.max(0,b-c))+a};var I=function(a){var b=document;oa(a);b="string"===typeof a?b.getElementById(a):a;return z(b,"No element found with id: "+a)},Ua=function(a,b){Ba(b,function(c,d){"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Ta.hasOwnProperty(d)?a.setAttribute(Ta[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},Ta={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Xa=function(a,b,c){var d=arguments,e=document,f=d[1],g=Va(e,String(d[0]));f&&("string"===typeof f?g.className=f:Array.isArray(f)?g.className=f.join(" "):Ua(g,f));2<d.length&&Wa(e,g,d);return g},Wa=function(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var f=c[e];if(!ia(f)||ja(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(ja(f)){var g=
"function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}qa(g?ra(f):f,d)}}},Va=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};var Ya=function(a,b){this.j=a;this.D=b;this.i=I("h5-player");J=this.i.clientWidth;K=this.i.clientHeight;this.C=I("h5-ad-container")||Xa("DIV");this.o=!1;this.m=null;this.v=new window.google.ima.AdDisplayContainer(this.C,this.i);this.l=new window.google.ima.AdsLoader(this.v);this.u=[];this.g=null;this.B=I("play-button");a=this.l.getSettings();a.setPlayerType("h5_vsi");a.setDisableCustomPlaybackForIOS10Plus(!0);this.l.addEventListener(window.google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,
this.La,!1,this);this.l.addEventListener(window.google.ima.AdErrorEvent.Type.AD_ERROR,this.ea,!1,this);var c=null;window.addEventListener("resize",function(){this.g&&(clearTimeout(c),c=u.setTimeout(function(){J=this.i.clientWidth;K=this.i.clientHeight;this.g.resize(this.i.clientWidth,this.i.clientHeight,window.google.ima.ViewMode.NORMAL)}.bind(this),100))}.bind(this))},J,K,Za=function(){var a={},b=I("omsdk-rules-container"),c=b.querySelectorAll(".omsdk-verification-vendor-select"),d=b.querySelectorAll(".omsdk-access-mode-select");
c.forEach(function(e,f){a[google.ima.OmidVerificationVendor[c[f].value]]=google.ima.OmidAccessMode[d[f].value]});return a};m=Ya.prototype;m.setVpaidMode=function(a){this.l.getSettings().setVpaidMode($a[a])};m.pause=function(){this.g&&this.g.pause()};m.resume=function(){this.g&&this.g.resume()};m.setVolume=function(a){this.g&&this.g.setVolume(a)};m.getVolume=function(){return this.g?this.g.getVolume():-1};
m.getCurrentTime=function(){return this.g&&this.m?this.m.getDuration()-this.g.getRemainingTime():-1};m.getDuration=function(){return this.g&&this.m?this.m.getDuration():-1};
m.La=function(a){this.j.log("Ads loaded.");var b=new window.google.ima.AdsRenderingSettings;b.mimeTypes=this.u;b.enablePreloading=I("preloading-true").checked;a=this.g=a.getAdsManager(this.D.g,b);a.addEventListener(window.google.ima.AdEvent.Type.CONTENT_PAUSE_REQUESTED,this.Na,!1,this);a.addEventListener(window.google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED,this.Oa,!1,this);a.addEventListener(window.google.ima.AdErrorEvent.Type.AD_ERROR,this.ea,!1,this);for(b=0;b<ab.length;b++)a.addEventListener(ab[b],
this.Ka,!1,this);a.init(this.i.clientWidth,this.i.clientHeight,window.google.ima.ViewMode.NORMAL);a.start()};m.Na=function(){var a=this.j;a.j=!0;a.g.pause()};m.Oa=function(){this.o||bb(this.j)};
m.Ka=function(a){this.j.o&&this.j.o(a);var b=a.type;b!=window.google.ima.AdEvent.Type.AD_PROGRESS&&this.j.log("Ad event: "+b);console.log("Ad event: "+b);switch(a.type){case window.google.ima.AdEvent.Type.STARTED:this.m=a.getAd();this.m.isLinear()||bb(this.j);break;case window.google.ima.AdEvent.Type.LOG:(a=a.getAdData())&&a.adError&&this.j.log("Non-fatal error occurred: "+a.adError.getMessage());break;case window.google.ima.AdEvent.Type.DURATION_CHANGE:this.m=a.getAd();break;case window.google.ima.AdEvent.Type.INTERACTION:this.j.log("Interaction ID: "+
a.getAdData().id);break;case window.google.ima.AdEvent.Type.PAUSED:this.B.className="play-button"}};m.ea=function(a){this.j.log("Ad error: "+a.getError().toString());this.g&&this.g.destroy();bb(this.j)};
var ab=[window.google.ima.AdEvent.Type.AD_METADATA,window.google.ima.AdEvent.Type.AD_PROGRESS,window.google.ima.AdEvent.Type.ALL_ADS_COMPLETED,window.google.ima.AdEvent.Type.CLICK,window.google.ima.AdEvent.Type.COMPLETE,window.google.ima.AdEvent.Type.DURATION_CHANGE,window.google.ima.AdEvent.Type.FIRST_QUARTILE,window.google.ima.AdEvent.Type.IMPRESSION,window.google.ima.AdEvent.Type.INTERACTION,window.google.ima.AdEvent.Type.LINEAR_CHANGED,window.google.ima.AdEvent.Type.LOADED,window.google.ima.AdEvent.Type.LOG,
window.google.ima.AdEvent.Type.MIDPOINT,window.google.ima.AdEvent.Type.PAUSED,window.google.ima.AdEvent.Type.RESUMED,window.google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED,window.google.ima.AdEvent.Type.SKIPPED,window.google.ima.AdEvent.Type.STARTED,window.google.ima.AdEvent.Type.THIRD_QUARTILE,window.google.ima.AdEvent.Type.USER_CLOSE,window.google.ima.AdEvent.Type.VOLUME_CHANGED,window.google.ima.AdEvent.Type.VOLUME_MUTED],$a={"vpaid-enabled":window.google.ima.ImaSdkSettings.VpaidMode.ENABLED,"vpaid-insecure":window.google.ima.ImaSdkSettings.VpaidMode.INSECURE,
"vpaid-disabled":window.google.ima.ImaSdkSettings.VpaidMode.DISABLED};var cb=function(){this.g=I("h5-player");this.i=null},db=function(a,b){Aa?(a.i=b,a.g.addEventListener("loadedmetadata",a.i,!1),a.g.load()):b()},eb=function(a){a.i&&a.g.removeEventListener("loadedmetadata",a.i,!1)};m=cb.prototype;m.load=function(){this.g.load()};m.play=function(){this.g.play()};m.pause=function(){this.g.pause()};m.setVolume=function(a){this.g.volume=a};m.getCurrentTime=function(){return this.g.currentTime};m.getDuration=function(){return this.g.duration};var L=function(){this.J=this.C=this.j=!1;this.o=this.v=this.H=null;this.g=new cb;this.i=new Ya(this,this.g);this.D=this.B="";this.u=[];this.m=this.l=0;var a=this.g,b=w(this.K,this);a.g.addEventListener("ended",b,!1)};L.prototype.setVpaidMode=function(a){this.i.setVpaidMode(a)};L.prototype.setVolume=function(a){this.i.setVolume(a);this.g.setVolume(a)};
var gb=function(a,b){a.B=b;fb(a);db(a.g,function(){eb(a.g);var c=a.i,d=a.B;if(d.includes("%%"))c.j.log("The ad contains macros such as %%WINNING_PRICE%%. Please expand all macros prior to testing ad tags in VSI player.");else{var e=new window.google.ima.AdsRequest;e.adTagUrl=d;e.linearAdSlotWidth=e.nonLinearAdSlotWidth=J;e.linearAdSlotHeight=e.nonLinearAdSlotHeight=K;I("yes-include-omsdk-rules").checked&&(e.omidAccessModeRules=Za());c.l.requestAds(e)}})},hb=function(a,b){a.D=b;fb(a);db(a.g,function(){eb(a.g);
var c=a.i,d=a.D,e=new window.google.ima.AdsRequest;J=c.i.clientWidth;K=c.i.clientHeight;e.adsResponse=d;e.linearAdSlotWidth=e.nonLinearAdSlotWidth=c.i.clientWidth;e.linearAdSlotHeight=e.nonLinearAdSlotHeight=c.i.clientHeight;I("yes-include-omsdk-rules").checked&&(e.omidAccessModeRules=Za());c.l.requestAds(e)})},fb=function(a){var b=a.i;b.g&&b.g.destroy();b.l&&b.l.contentComplete();b.o=!1;a.i.u=a.u;setInterval(w(a.I,a),250);a.C||(a.g.load(),a.i.v.initialize(),a.C=!0);a.J&&(a.g.g.currentTime=0);a.J=
!0};L.prototype.play=function(){setInterval(w(this.I,this),250);this.j?this.i.resume():this.g.play()};L.prototype.pause=function(){this.j?this.i.pause():this.g.pause()};L.prototype.log=function(a){this.H(a)};var bb=function(a){a.g.play();a.j=!1};L.prototype.I=function(){this.j?(this.l=this.i.getCurrentTime(),this.m=this.i.getDuration()):(this.l=this.g.getCurrentTime(),this.m=this.g.getDuration());this.v({currentTime:this.l,duration:this.m})};L.prototype.K=function(){var a=this.i;a.o=!0;a.l.contentComplete()};
ha("VideoSuiteInspector.players.h5player.HTML5Player",L);!E("Android")||za();za();E("Safari")&&(za()||(F()?0:E("Coast"))||(F()?0:E("Opera"))||(F()?0:E("Edge"))||(F()?ya("Microsoft Edge"):E("Edg/"))||F()&&ya("Opera"));z(!0);var ib="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;z(13===Math.round(Math.log2(Math.max.apply(Math,ea(Object.values({gb:1,eb:2,cb:4,kb:8,jb:16,hb:32,Va:64,ob:128,bb:256,ab:512,fb:1024,Ya:2048,mb:4096,Za:8192}))))));var jb=Object.getOwnPropertyDescriptor(Array.prototype,"Ja");
Object.defineProperties(Array.prototype,{Ja:{get:function(){function a(e,f){e&b&&c.push(f)}var b=kb(this),c=[];a(1,"IS_REPEATED_FIELD");a(2,"IS_IMMUTABLE_ARRAY");a(4,"IS_API_FORMATTED");a(4096,"STRING_FORMATTED");a(8192,"GBIGINT_FORMATTED");a(8,"ONLY_MUTABLE_VALUES");a(32,"MUTABLE_REFERENCES_ARE_OWNED");a(64,"CONSTRUCTED");a(128,"TRANSFERRED");a(256,"HAS_SPARSE_OBJECT");a(512,"HAS_MESSAGE_ID");a(2048,"FROZEN_ARRAY");var d=lb(b);536870912!==d&&c.push("pivot: "+d);d=c.join(",");return jb?jb.get.call(this)+
"|"+d:d},configurable:!0,enumerable:!1}});var kb=ib?function(a){pa(a,"state is only maintained on arrays.");return a[ib]|0}:function(a){pa(a,"state is only maintained on arrays.");return a.g|0};function lb(a){a=a>>14&1023;return 0===a?536870912:a};var mb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;Object.freeze(new function(){});Object.freeze(new function(){});var nb=function(){throw Error("please construct maps as mutable then call toImmutable");};if(mb){var ob=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},pb={};Object.defineProperties(nb,(pb[Symbol.hasInstance]={value:ob,configurable:!1,writable:!1,enumerable:!1},pb));z(nb[Symbol.hasInstance]===ob,"defineProperties did not work: was it monkey-patched?")};if("undefined"!==typeof Proxy){var M=qb;new Proxy({},{getPrototypeOf:M,setPrototypeOf:M,isExtensible:M,preventExtensions:M,getOwnPropertyDescriptor:M,defineProperty:M,has:M,get:M,set:M,deleteProperty:M,apply:M,construct:M})}function qb(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");throw Error();};function rb(){};(function(){var a=u.jspbGetTypeName;u.jspbGetTypeName=a?function(b){return a(b)||void 0}:rb})();var sb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),tb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var N=function(a){this.i=this.u=this.l="";this.v=null;this.o=this.g="";this.m=!1;var b;a instanceof N?(this.m=a.m,ub(this,a.l),this.u=a.u,this.i=a.i,vb(this,a.v),this.g=a.g,wb(this,xb(a.j)),this.o=a.o):a&&(b=String(a).match(sb))?(this.m=!1,ub(this,b[1]||"",!0),this.u=O(b[2]||""),this.i=O(b[3]||"",!0),vb(this,b[4]),this.g=O(b[5]||"",!0),wb(this,b[6]||"",!0),this.o=O(b[7]||"")):(this.m=!1,this.j=new P(null,this.m))};
N.prototype.toString=function(){var a=[],b=this.l;b&&a.push(Q(b,yb,!0),":");var c=this.i;if(c||"file"==b)a.push("//"),(b=this.u)&&a.push(Q(b,yb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.v,null!=c&&a.push(":",String(c));if(c=this.g)this.i&&"/"!=c.charAt(0)&&a.push("/"),a.push(Q(c,"/"==c.charAt(0)?zb:Ab,!0));(c=this.j.toString())&&a.push("?",c);(c=this.o)&&a.push("#",Q(c,Bb));return a.join("")};
N.prototype.resolve=function(a){var b=new N(this),c=!!a.l;c?ub(b,a.l):c=!!a.u;c?b.u=a.u:c=!!a.i;c?b.i=a.i:c=null!=a.v;var d=a.g;if(c)vb(b,a.v);else if(c=!!a.g){if("/"!=d.charAt(0))if(this.i&&!this.g)d="/"+d;else{var e=b.g.lastIndexOf("/");-1!=e&&(d=b.g.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.g=d:c=""!==a.j.toString();c?wb(b,xb(a.j)):c=!!a.o;c&&(b.o=a.o);return b};
var ub=function(a,b,c){a.l=c?O(b,!0):b;a.l&&(a.l=a.l.replace(/:$/,""))},vb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.v=b}else a.v=null},wb=function(a,b,c){b instanceof P?(a.j=b,Cb(a.j,a.m)):(c||(b=Q(b,Db)),a.j=new P(b,a.m))},O=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Q=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Eb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Eb=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},yb=/[#\/\?@]/g,Ab=/[#\?:]/g,zb=/[#\?]/g,Db=/[#\?@]/g,Bb=/#/g,P=function(a,b){this.i=this.g=null;this.j=a||null;this.l=!!b},R=function(a){a.g||(a.g=new Map,a.i=0,a.j&&tb(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};P.prototype.add=function(a,b){R(this);this.j=null;a=S(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i=A(this.i)+1;return this};
var Fb=function(a,b){R(a);b=S(a,b);a.g.has(b)&&(a.j=null,a.i=A(a.i)-a.g.get(b).length,a.g.delete(b))};P.prototype.clear=function(){this.g=this.j=null;this.i=0};var Gb=function(a,b){R(a);b=S(a,b);return a.g.has(b)};P.prototype.forEach=function(a,b){R(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
var Hb=function(a,b){R(a);var c=[];if("string"===typeof b)Gb(a,b)&&(c=c.concat(a.g.get(S(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};P.prototype.set=function(a,b){R(this);this.j=null;a=S(this,a);Gb(this,a)&&(this.i=A(this.i)-this.g.get(a).length);this.g.set(a,[b]);this.i=A(this.i)+1;return this};P.prototype.get=function(a,b){if(!a)return b;a=Hb(this,a);return 0<a.length?String(a[0]):b};
P.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Hb(this,d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.j=a.join("&")};
var xb=function(a){var b=new P;b.j=a.j;a.g&&(b.g=new Map(a.g),b.i=a.i);return b},S=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},Cb=function(a,b){b&&!a.l&&(R(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Fb(this,d),Fb(this,e),0<c.length&&(this.j=null,this.g.set(S(this,e),ra(c)),this.i=A(this.i)+c.length))},a));a.l=b};var Ib=Ra;Qa||(Qa=new Pa);Ib(Qa,"google3.javascript.ads.imalib.common.host_utils");var Jb=function(a){var b=Va(document,"BODY");b.textContent=a;z(b.innerHTML==b.textContent,"String has HTML original: %s, escaped: %s",a,b.innerHTML);return a};var Kb={ia:["BC","AD"],ha:["Before Christ","Anno Domini"],la:"JFMAMJJASOND".split(""),ra:"JFMAMJJASOND".split(""),ka:"January February March April May June July August September October November December".split(" "),qa:"January February March April May June July August September October November December".split(" "),na:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ta:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),xa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
va:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),pa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ua:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ib:"SMTWTFS".split(""),sa:"SMTWTFS".split(""),oa:["Q1","Q2","Q3","Q4"],ma:["1st quarter","2nd quarter","3rd quarter","4th quarter"],fa:["AM","PM"],Wa:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],nb:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],Xa:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],O:6,
pb:[5,6],P:5},T=Kb;T=Kb;var Lb=function(a,b,c,d,e){a=new Date(a,b,c);e=e||0;return a.valueOf()+864E5*(((void 0!==d?d:3)-e+7)%7-((a.getDay()+6)%7-e+7)%7)};var Mb=function(){},U=function(a){if("number"==typeof a){var b=new Mb;b.m=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",G(c,2));c=d.join("")}b.j=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=Nb(a);b.l=[c,c];b.g={lb:a,Z:a};b.i=[];return b}b=new Mb;b.j=a.id;b.m=-a.std_offset;b.l=a.names;b.g=a.names_ext;b.i=a.transitions;return b},Nb=function(a){var b=
["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(G(Math.floor(a/60)%100,2),":",G(a%60,2));return b.join("")},Ob=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.i.length&&b>=a.i[c];)c+=2;return 0==c?0:a.i[c-1]},Pb=function(a,b){a=a.m-Ob(a,b);return-1440===a?0:a};var Sb=function(){z(!0,"Pattern must be defined");z(void 0!==T,"goog.i18n.DateTimeSymbols or explicit symbols must be defined");this.i=[];this.g=T;var a="mm:ss";for(Qb&&(a=a.replace(/\u200f/g,""));a;){for(var b=a,c=0;c<Rb.length;++c){var d=a.match(Rb[c]);if(d){var e=d[0];a=a.substring(e.length);0==c&&("''"==e?e="'":(e=e.substring(1,"'"==d[1]?e.length-1:e.length),e=e.replace(/''/g,"'")));this.i.push({text:e,type:c});break}}if(b===a)throw Error("Malformed pattern part: "+a);}},Rb=[/^'(?:[^']|'')*('|$)/,
/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|b+|B+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEabBhKHcLQdmsvVwzZ]+/],V=function(a){return a.getHours?a.getHours():0};
Sb.prototype.format=function(a,b){if(!a)throw Error("The date to format must be non-null.");var c=b?6E4*(a.getTimezoneOffset()-Pb(b,a)):0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(d=new Date(d.getTime()+6E4*(d.getTimezoneOffset()-a.getTimezoneOffset())),e=new Date(a.getTime()+(c+(0<c?-864E5:864E5))));c=[];for(var f=0;f<this.i.length;++f){var g=this.i[f].text;1==this.i[f].type?c.push(Tb(this,g,a,d,e,b)):c.push(g)}return c.join("")};
var W=function(a,b){b=String(b);a=a.g||T;if(void 0!==a.Ba){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.Ba+e-48):b.charAt(d))}b=c.join("")}return b},Qb=!1,X=function(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("The date to format has no time (probably a goog.date.Date). Use Date or goog.date.DateTime, or use a pattern without time fields.");},Ub=function(a,b){X(b);b=V(b);return a.g.fa[12<=b&&24>b?1:0]},Tb=function(a,b,c,d,e,f){var g=
b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=g?a.g.ha[c]:a.g.ia[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==g&&(c%=100),W(a,G(c,g));case "Y":return c=(new Date(Lb(d.getFullYear(),d.getMonth(),d.getDate(),a.g.P,a.g.O))).getFullYear(),0>c&&(c=-c),2==g&&(c%=100),W(a,G(c,g));case "M":a:switch(c=d.getMonth(),g){case 5:g=a.g.la[c];break a;case 4:g=a.g.ka[c];break a;case 3:g=a.g.na[c];break a;default:g=W(a,G(c+1,g))}return g;case "k":return X(e),W(a,G(V(e)||24,g));case "S":return W(a,
(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).slice(2)+(3<g?G(0,g-3):""));case "E":return c=d.getDay(),4<=g?a.g.xa[c]:a.g.pa[c];case "a":return Ub(a,e);case "b":return Ub(a,e);case "B":return Ub(a,e);case "h":return X(e),W(a,G(V(e)%12||12,g));case "K":return X(e),W(a,G(V(e)%12,g));case "H":return X(e),W(a,G(V(e),g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.g.sa[c];break a;case 4:g=a.g.va[c];break a;case 3:g=a.g.ua[c];break a;default:g=W(a,G(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=
a.g.ra[c];break a;case 4:g=a.g.qa[c];break a;case 3:g=a.g.ta[c];break a;default:g=W(a,G(c+1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),4>g?a.g.oa[c]:a.g.ma[c];case "d":return W(a,G(d.getDate(),g));case "m":return X(e),W(a,G(e.getMinutes?e.getMinutes():0,g));case "s":return X(e),W(a,G(e.getSeconds(),g));case "v":return(f||U(c.getTimezoneOffset())).j;case "V":return a=f||U(c.getTimezoneOffset()),2>=g?a.j:0<Ob(a,c)?void 0!==a.g.ga?a.g.ga:a.g.DST_GENERIC_LOCATION:void 0!==a.g.Z?a.g.Z:a.g.STD_GENERIC_LOCATION;
case "w":return c=Lb(e.getFullYear(),e.getMonth(),e.getDate(),a.g.P,a.g.O),W(a,G(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||U(c.getTimezoneOffset()),4>g?a.l[0<Ob(a,c)?2:0]:a.l[0<Ob(a,c)?3:1];case "Z":return b=f||U(c.getTimezoneOffset()),4>g?(g=-Pb(b,c),a=[0>g?"-":"+"],g=Math.abs(g),a.push(G(Math.floor(g/60)%100,2),G(g%60,2)),g=a.join("")):g=W(a,Nb(Pb(b,c))),g;default:return""}};var Y=function(a,b){this.g=a;this.m=!1;this.ba=I("vast-tag-radio");this.i=I("vast-tag-url");this.M=I("vast-xml");this.Ia=I("http-warning");this.T=I("advanced-controls-arrow");this.B=I("share-link-button");this.aa=I("shorten-share-link-checkbox-div");this.L=I("shorten-share-link-checkbox");this.o=I("share-link-text");this.U=I("advanced-controls");this.ca=I("yes-include-omsdk-rules");this.Fa=I("no-include-omsdk-rules");this.v=I("omsdk-rules-container");this.R=I("add-omsdk-rule-button");this.Ca=I("template-omsdk-rule");
this.u=I("play-button");this.ya=I("current-time");this.za=I("duration-time");this.K=I("progress-list");this.Ga=I("play-progress");this.D=I("volume-button");this.C=I("report-events");this.I="";this.J=b;this.H=this.X=!1;this.l=this.j=0;this.W=[];this.V=[];Vb(this);Wb(this);if(a=this.J)if(a=(new N(a)).j.get("tag"))this.i.value=decodeURIComponent(a.replace(/\+/g," "));a=this.g;b=w(this.Aa,this);a.H=b;a=this.g;b=w(this.ja,this);a.v=b;a=this.g;b=w(this.Da,this);a.o=b},Vb=function(a){var b=I("companion-section");
Xb.forEach(function(c){var d=Xa("DIV");d.id=c.name;d.className="vsi-companion-ad";d.name=c.name;b.appendChild(d);a.W.push(d);googletag.defineUnit(c.name,["fluid",[c.width,c.height]],c.name).addService(googletag.companionAds())});googletag.pubads().collapseEmptyDivs();googletag.enableServices()},Wb=function(a){[{id:"sample-tag-link",G:a.Ra},{id:"vast-xml-radio",G:a.Ua},{id:"advanced-controls-header",G:a.Ma},{id:"test-ad-button",G:a.Sa},{id:"clear-log-button",G:a.wa}].forEach(function(b){var c=I(b.id);
Z(a,c,b.G)});Z(a,a.ba,a.Ta);Z(a,a.B,a.Y);Z(a,a.L,a.Y);Z(a,a.u,a.Pa);Z(a,a.K,a.Qa);Z(a,a.D,a.N);Z(a,a.ca,a.da);Z(a,a.Fa,a.da);Z(a,a.R,a.Ea);a.D.value="max";a.I=a.i.value;setInterval(w(a.Ha,a),100)};m=Y.prototype;m.destroy=function(){this.V.forEach(function(a){var b=a.element;a=a.G;b.addEventListener?b.removeEventListener("click",a,!1):b.attachEvent&&b.detachEvent("onclick",a)})};m.Ta=function(){Yb(this,!0);Zb(this);this.i.style.display="inline";this.M.style.display="none"};
m.Ua=function(){Yb(this,!1);Zb(this);this.i.style.display="none";this.M.style.display="inline"};m.Ra=function(){this.i.value="https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator="};m.Ha=function(){if(this.I!=this.i.value){var a=new N(this.i.value);this.Ia.style.display="http"==a.l?"inline-block":"none";this.I=this.i.value}};
m.Sa=function(){$b(this);ac(this);bc(this);this.ba.checked?gb(this.g,this.i.value):hb(this.g,this.M.value);this.u.className="pause-button"};var ac=function(a){var b=[];[].concat(ea(document.getElementsByClassName("mime-checkbox"))).forEach(function(c){c.checked&&b.push(c.getAttribute("id"))});a.g.u=b},bc=function(a){[].concat(ea(document.getElementsByName("vpaid-radio-group"))).forEach(function(b){b.checked&&a.g.setVpaidMode(b.id)})};
Y.prototype.Y=function(){this.aa.style.display="inline";var a="https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector";this.J?a=this.J:document.referrer&&document.referrer.includes("vastinspector")&&(a=document.referrer);if(a){a=new N(a);if(""!==encodeURIComponent(this.i.value)){var b=encodeURIComponent(this.i.value);a.j.set("tag",b)}a=a.toString();this.L.checked?cc(this,a):dc(this,a)}else this.o.value="Error: could not generate sharable URL"};
var ec=function(a,b){gapi.client.setApiKey("AIzaSyDhwO-mwC66FOUtx1gVxH9nnWWz1je5UlI");gapi.client.load("urlshortener","v1",function(){a.X=!0;cc(a,b)})},cc=function(a,b){a.X?gapi.client.urlshortener.url.insert({resource:{longUrl:b}}).execute(function(c){dc(a,c.id)}):ec(a,b)},dc=function(a,b){a.o.value=b;a.o.style.display="block";a.o.select()},Zb=function(a){a.o.value="";a.o.style.display="none"},Yb=function(a,b){b?(a.B.disabled="",a.B.classList.add("button-blue")):(a.B.disabled="disabled",a.B.classList.remove("button-blue"),
a.aa.style.display="none",a.L.checked="")},$b=function(a){a.W.forEach(function(b){b.textContent=""})};m=Y.prototype;m.Ma=function(){this.H?(this.T.textContent="\u25b8",this.U.style.display="none"):(this.T.textContent="\u25be",this.U.style.display="block");this.H=!this.H};m.da=function(){this.ca.checked?this.v.classList.remove("hidden"):this.v.classList.add("hidden")};
m.Ea=function(){var a=this.Ca.content.cloneNode(!0),b=a.querySelector(".omsdk-setting-remove-button");this.v.appendChild(a);var c=this.v.querySelectorAll(".omsdk-rule:last-child")[0];this.v.appendChild(this.R);b.addEventListener("click",function(){c.remove()})};m.Pa=function(){"play-button"===this.u.className?(this.u.className="pause-button",this.g.play()):(this.u.className="play-button",this.g.pause())};
m.Qa=function(a){if(this.l&&this.j){var b=this.K.getBoundingClientRect().left;a=(a.clientX-b)/this.K.clientWidth;this.j=0>a?0:1<a?this.l:this.l*a;this.j=Math.round(this.j);a=this.g;a.j||(a.g.g.currentTime=this.j);fc(this)}};m.N=function(){(this.m=!this.m)?(this.g.setVolume(0),this.D.value="off"):(this.g.setVolume(1),this.D.value="max")};
m.ja=function(a){this.j=-1<a.currentTime?a.currentTime:0;this.l=-1<a.duration?a.duration:0;a=new Sb;this.ya.textContent=Jb(a.format(new Date(0,0,0,0,0,this.j)));this.za.textContent=Jb(a.format(new Date(0,0,0,0,0,this.l)));fc(this)};m.Da=function(a){switch(a.type){case window.google.ima.AdEvent.Type.VOLUME_MUTED:this.m||this.N();break;case window.google.ima.AdEvent.Type.VOLUME_CHANGED:a=this.g.i.getVolume(),(0==a&&!this.m||0!=a&&this.m)&&this.N()}};
var fc=function(a){a.Ga.style.width=0<a.l?Math.round(a.j/a.l*100)+"%":"0"};Y.prototype.Aa=function(a){a="("+(new Date).toLocaleTimeString()+") "+a;var b=document.createElement("li");b.appendChild(document.createTextNode(a));this.C.appendChild(b);this.C.scrollTop=this.C.scrollHeight};Y.prototype.wa=function(){this.C.textContent=""};
var Z=function(a,b,c){c=c.bind(a);b.addEventListener?b.addEventListener("click",c,!1):b.attachEvent&&b.attachEvent("onclick",c);a.V.push({element:b,G:c})},Xb=[{name:"leaderboard",width:728,height:90},{name:"mediumRectangle",width:300,height:250},{name:"rectangle",width:180,height:150},{name:"button2",width:120,height:60},{name:"microBar",width:88,height:31},{name:"smallRectangle",width:300,height:60},{name:"threeByOne",width:300,height:100},{name:"mobileBanner",width:320,height:50},{name:"smallBanner",
width:468,height:60},{name:"halfPageAd",width:300,height:600},{name:"wideSkyscraper",width:160,height:600}];ha("VideoSuiteInspector.ui.UserInterface",Y,window);}).call(this);
})();